### ISSUE TITLE
Changes in main.yaml under fio-bench/tasks not reflected

### ISSUE THREAD

**Issue by shekharberry** [jtaleric/benchmark-operator#13]
Hi,

I was trying to tweak main.yaml to understand how Fio-bench works but any change done to main.yaml is not reflected once I deploy the CR.
Say for eg:
Even If i just change the name of Configmap to fio-test_shekhar and redeploy the CR the configmap is still created with name fio-test.

name: Generate fio test
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: fio-test_shekhar
        namespace: '{{ meta.namespace }}'
      data:
        fiojob: "{{ lookup('template', 'job.fio.seq_write') }}"
  when: fio.clients > 0

oc get configmap
NAME                      DATA      AGE
benchmark-operator-lock   0         3h
fio-test                  1         1h

Am I missing something??

**Comment by dustinblack** [comment]
I think you already had a chat with @jtaleric about this, but the gist of it is that any changes to the roles mean that the operator image has to be rebuilt. You'll need the operator-sdk to complete this, and following our current test build process you will need an account on quay.io to upload your operator:testing images to.

```
# operator-sdk build quay.io/<username>/benchmark-operator:testing
# docker push quay.io/<username>/benchmark-operator:testing
```

You will also need to edit deploy/operator.yaml to point to your quay.io image URL.

```
...
spec:
...
  template:
...
    spec:
...
      containers:
        - name: benchmark-operator
          image: quay.io/jtaleric/benchmark-operator:latest
...
```

**Comment by jtaleric** [comment]
@shekharberry hey - did you make progress? If so, can we close this issue out?

**Comment by shekharberry** [comment]
Yes, I could progress. Thanks for the help. We can close the issue.
